### ISSUE TITLE
Build fails without `-latomic` with GCC 11.2.1 on Gentoo Linux RISC-V

### ISSUE THREAD

**Issue by infiWang** [fish-shell/fish-shell#8850]
`master` refuse to compile with GCC 11.2.1 on Gentoo Linux RISC-V, complains about missing `__atomic_*` symbols.

```
[ 89%] Building CXX object CMakeFiles/fish.dir/src/fish.cpp.o
[ 90%] Linking CXX executable fish
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/../../../../riscv64-unknown-linux-gnu/bin/ld: libfishlib.a(topic_monitor.cpp.o): in function `owning_lock<topic_monitor_t::data_t>::owning_lock()':
/home/gns/src/fish-shell/src/common.h:400: undefined reference to `__atomic_compare_exchange_1'
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/../../../../riscv64-unknown-linux-gnu/bin/ld: libfishlib.a(topic_monitor.cpp.o): in function `topic_monitor_t::post(topic_t)':
/home/gns/src/fish-shell/src/topic_monitor.cpp:134: undefined reference to `__atomic_compare_exchange_1'
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/../../../../riscv64-unknown-linux-gnu/bin/ld: libfishlib.a(topic_monitor.cpp.o): in function `std::mutex::lock()':
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/include/g++-v11/bits/std_mutex.h:104: undefined reference to `__atomic_compare_exchange_1'
/usr/lib/gcc/riscv64-unknown-linux-gnu/11.2.1/../../../../riscv64-unknown-linux-gnu/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status 
```

RISC-V only has 4/4+8 byte atomic instruction for riscv32/riscv64 respectively, different from many other ISAs.

After Glibc 2.34, `-pthread` no longer inherit linking of `libatomic`. Since GCC has yet implemented atomics inlining  for RISC-V, plus the possibility of working with an old toolchain, a fix might be wanted.

Build log:
[CMakeOutput.log](https://github.com/fish-shell/fish-shell/files/8403890/CMakeOutput.log)
[CMakeError.log](https://github.com/fish-shell/fish-shell/files/8403891/CMakeError.log)

**Comment by ridiculousfish** [comment]
Merged as 9f98d2ec5dce715c3c565bb4ec353cd989101e16, thank you! Wild architecture.
