### ISSUE TITLE
error: field has incomplete type 'history_impl_t'

### ISSUE THREAD

**Issue by ryandesign** [fish-shell/fish-shell#7023]
Hi, I just updated [fish in MacPorts](https://ports.macports.org/port/fish) to 3.1.2 and noticed that it [failed to build on our OS X 10.9 build machine](https://build.macports.org/builders/ports-10.9_x86_64-builder/builds/119389/steps/install-port/logs/stdio) when compiling with Clang from Xcode 6.2 (`Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)`). The error is:

```
In file included from /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_shells_fish/fish/work/fish-3.1.2/src/builtin.h:9:
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_shells_fish/fish/work/fish-3.1.2/src/common.h:493:10: error: field has incomplete type 'history_impl_t'
    Data data;
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:1444:55: note: in instantiation of template class 'owning_lock<history_impl_t>' requested here
typename __select_2nd<decltype((_VSTD::declval<_Tp>() = _VSTD::declval<_Arg>())), true_type>::type
                                                      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:1463:22: note: while substituting deduced template arguments into function template '__is_assignable_test' [with _Tp = std::__1::default_delete<owning_lock<history_impl_t> > &, _Arg = std::__1::default_delete<owning_lock<history_impl_t> >]
            decltype(__is_assignable_test(declval<_Tp>(), declval<_Arg>()))
                     ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/type_traits:1474:14: note: in instantiation of template class 'std::__1::__is_assignable_imp<std::__1::default_delete<owning_lock<history_impl_t> > &, std::__1::default_delete<owning_lock<history_impl_t> > &&, false>' requested here
    : public __is_assignable_imp<_Tp, _Arg> {};
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2552:17: note: in instantiation of template class 'std::__1::is_assignable<std::__1::default_delete<owning_lock<history_impl_t> > &, std::__1::default_delete<owning_lock<history_impl_t> > &&>' requested here
                is_assignable<deleter_type&, _Ep&&>::value,
                ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2454:29: note: while substituting deduced template arguments into function template 'operator=' [with _Up = owning_lock<history_impl_t>, _Ep = std::__1::default_delete<owning_lock<history_impl_t> >]
class _LIBCPP_TYPE_VIS_ONLY unique_ptr
                            ^
/opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_shells_fish/fish/work/fish-3.1.2/src/history.h:66:19: note: forward declaration of 'history_impl_t'
    friend struct history_impl_t;
                  ^
```

But it [built successfully on our Mac OS X 10.6 build machine](https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/26766/steps/install-port/logs/stdio) when compiling with the newer Clang 9 compiler as installed by MacPorts.

This makes me think that fish requires a newer compiler than we thought, perhaps inadvertently. Is this the kind of problem that could easily be fixed in the fish source code or should we just require a newer compiler?

The readme says fish requires "a C++11 compiler (g++ 4.8 or later, or clang 3.3 or later)". Is that still accurate or does it now require a newer C++ language standard?

**Comment by faho** [comment]
See also #4029.

**Comment by ridiculousfish** [comment]
I was able to get fish working on 10.9 with Xcode 6.2 by guarding thread_local (84e0c8d32e46279060739ffb3f2320c9c7c957bc) and rejiggering some unique_ptr (1fd0cd5510596145e20525dee15208b44a0f5c15). Thanks for filing!
