### ISSUE TITLE
fails to build with Apple gcc 4.0.1 (5493) on OS X 10.5 (ppc)

### ISSUE THREAD

**Issue by anders** [fish-shell/fish-shell#431]
Revision: 332cda6

Build error:

```
g++ -g -O2 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -fno-optimize-sibling-calls -Wall -DLOCALEDIR=\"/usr/local/share/locale\" -DPREFIX=L\"/usr/local\" -DDATADIR=L\"/usr/local/share\" -DSYSCONFDIR=L\"/usr/local/etc\"    -c -o history.o history.cpp
history.cpp: In function 'file_id_t history_file_identify(int)':
history.cpp:102: warning: passing negative value '-0x00000000000000001' for argument 2 to 'std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = dev_t, _T2 = ino_t]'
history.cpp:102: warning: passing negative value '-0x00000000000000001' for argument 2 to 'std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = dev_t, _T2 = ino_t]'
history.cpp: In constructor 'history_t::history_t(const wcstring&)':
history.cpp:480: warning: passing negative value '-0x00000000000000001' for argument 2 to 'std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = dev_t, _T2 = ino_t]'
history.cpp:480: warning: passing negative value '-0x00000000000000001' for argument 2 to 'std::pair<_T1, _T2>::pair(const _T1&, const _T2&) [with _T1 = dev_t, _T2 = ino_t]'
history.cpp: In member function 'void history_t::get_string_representation(wcstring&, const wcstring&)':
history.cpp:573: error: no match for 'operator<' in 'iter < std::vector<_Tp, _Alloc>::rend() [with _Tp = history_item_t, _Alloc = std::allocator<history_item_t>]()'
history.cpp:583: error: no match for 'operator!=' in 'iter != std::vector<_Tp, _Alloc>::rend() [with _Tp = size_t, _Alloc = std::allocator<size_t>]()'
lru.h: In member function 'void lru_cache_t<T>::iterator::operator++() [with node_type_t = history_lru_node_t]':
history.cpp:1261:   instantiated from here
lru.h:30: error: 'lru_node_t* lru_node_t::prev' is private
lru.h:221: error: within this context
make: *** [history.o] Error 1
```

**Comment by floam** [comment]
We can probably go back to using `const_reverse_iterator` in history.cpp when we're done supporting building on 10.5's Xcode SDK.

**Comment by floam** [comment]
I'm making a C++11 label. I'll sometimes mark old stuff like this that might be best looked at again after we switch.

**Comment by floam** [comment]
This can probably be undone now if we want.
