### PR TITLE
Fix compile error on OpenBSD

### PR DESCRIPTION
**Pull request by Darkshadow2**
## Description

This fixes a compile error introduced with 5dfb64b5476e16c847b2a385202182b84b86b6fe on OpenBSD.

The error is:
```
fish-shell/src/builtins/path.cpp:618:41: error: call to 'to_string' is ambiguous
                path_out(streams, opts, to_string(ret.change_seconds));
                                        ^~~~~~~~~
fish-shell/src/builtins/../wcstringutil.h:136:17: note: candidate function
inline wcstring to_string(long x) {
                ^
fish-shell/src/builtins/../wcstringutil.h:142:17: note: candidate function
inline wcstring to_string(unsigned long long x) {
                ^
fish-shell/src/builtins/../wcstringutil.h:148:17: note: candidate function
inline wcstring to_string(int x) { return to_string(static_cast<long>(x)); }
                ^
fish-shell/src/builtins/../wcstringutil.h:150:17: note: candidate function
inline wcstring to_string(size_t x) { return to_string(static_cast<unsigned long long>(x)); }
                ^
fish-shell/src/builtins/path.cpp:620:41: error: call to 'to_string' is ambiguous
                path_out(streams, opts, to_string(t - ret.change_seconds));
                                        ^~~~~~~~~
fish-shell/src/builtins/../wcstringutil.h:136:17: note: candidate function
inline wcstring to_string(long x) {
                ^
fish-shell/src/builtins/../wcstringutil.h:142:17: note: candidate function
inline wcstring to_string(unsigned long long x) {
                ^
fish-shell/src/builtins/../wcstringutil.h:148:17: note: candidate function
inline wcstring to_string(int x) { return to_string(static_cast<long>(x)); }
                ^
fish-shell/src/builtins/../wcstringutil.h:150:17: note: candidate function
inline wcstring to_string(size_t x) { return to_string(static_cast<unsigned long long>(x)); }
                ^
2 errors generated.
```

The problem turned out to be that OpenBSD's `time_t` is int64_t - long long.  This fixes the error by adding  a `to_string()` long long variant.

## TODOs:

- [ ] Changes to fish usage are reflected in user documentation/manpages.
- [ ] Tests have been added for regressions fixed
- [ ] User-visible changes noted in CHANGELOG.rst

### CODE REVIEW

**Comment by krobelus** [comment]
Thanks!
