### ISSUE TITLE
Current master fails to compile on Cygwin

### ISSUE THREAD

**Issue by Philipp15b** [fish-shell/fish-shell#1530]
The current master (7d47ec4c46792e70481959673fbfdec2adba1719) fails to compile on Cygwin (32-bit) with gcc 4.8.3:

```
env_universal_common.cpp: In function 'bool get_mac_address(unsigned char*, const char*)':
env_universal_common.cpp:983:53: error: 'socket' was not declared in this scope
     const int dummy = socket(AF_INET, SOCK_STREAM, 0);
                                                     ^
<builtin>: recipe for target 'env_universal_common.o' failed
make: *** [env_universal_common.o] Error 1
```
