### ISSUE TITLE
Fish 2.6.0 fails to build on FreeBSD 11.0

### ISSUE THREAD

**Issue by asomers** [fish-shell/fish-shell#4133]
Fish version 2.6.0
FreeBSD 11.0 amd64 or FreeBSD 10.3 amd64

Fish 2.6.0 defines its own `__assert` function, which conflicts with the OS's.  src/common.h attempts to solve that conflict by `#undef`ing `assert` and `__assert`, but on FreeBSD `__assert` is a function, not a macro.  The breakage is easy to fix by changing that function's name.

```
  CXX      obj/builtin_set.o
In file included from src/autoload.cpp:18:
In file included from ./src/autoload.h:11:
./src/lru.h:66:9: error: call to '__assert' is ambiguous
        assert(node != &mouth);
        ^~~~~~~~~~~~~~~~~~~~~~
./src/common.h:218:37: note: expanded from macro 'assert'
#define assert(e) (e) ? ((void)0) : __assert(#e, __FILE__, __LINE__, 0)
                                    ^~~~~~~~
/usr/include/assert.h:75:6: note: candidate function
void __assert(const char *, const char *, int, const char *) __dead2;
     ^
./src/common.h:232:19: note: candidate function
[[noreturn]] void __assert(const char *msg, const char *file, size_t line, int error);
                  ^
```
