### ISSUE TITLE
Failing to compile on OpenBSD 7.8

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#12192]
fish is currently failing to build on OpenBSD 7.8 with:

```
    Updating crates.io index
    Updating git repository `https://github.com/fish-shell/rust-pcre2`
     Locking 93 packages to latest Rust 1.85 compatible versions
      Adding generic-array v0.14.7 (available: v0.14.9)
      Adding lru v0.13.0 (available: v0.16.2)
  Downloaded cc v1.2.50
  Downloaded 1 crate (91.1KiB) in 0.18s
   Compiling libc v0.2.178
   Compiling typenum v1.19.0
   Compiling version_check v0.9.5
   Compiling find-msvc-tools v0.1.5
   Compiling shlex v1.3.0
   Compiling rsconf v0.2.2
   Compiling cfg-if v1.0.4
   Compiling memchr v2.7.6
   Compiling proc-macro2 v1.0.103
   Compiling rand_core v0.6.4
   Compiling siphasher v1.0.1
   Compiling zerocopy v0.8.31
   Compiling getrandom v0.3.4
   Compiling rand v0.8.5
   Compiling phf_shared v0.11.3
   Compiling option-ext v0.2.0
   Compiling generic-array v0.14.7
   Compiling regex-syntax v0.8.8
   Compiling quote v1.0.42
   Compiling unicode-ident v1.0.22
   Compiling cfg_aliases v0.2.1
   Compiling aho-corasick v1.1.4
   Compiling bstr v1.12.1
   Compiling phf_generator v0.11.3
   Compiling jobserver v0.1.34
   Compiling dirs-sys v0.5.0
   Compiling cc v1.2.50
   Compiling log v0.4.29
   Compiling same-file v1.0.6
   Compiling pkg-config v0.3.32
   Compiling cpufeatures v0.2.17
   Compiling rand_core v0.9.3
   Compiling walkdir v2.5.0
   Compiling dirs v6.0.0
   Compiling phf_codegen v0.11.3
   Compiling nix v0.30.1
   Compiling regex-automata v0.4.13
   Compiling crypto-common v0.1.7
   Compiling block-buffer v0.10.4
   Compiling digest v0.10.7
   Compiling sha2 v0.10.9
   Compiling fish-build-helper v0.0.0 (/home/darkshadow/Projects/UNIX/fish/crates/build-helper)
   Compiling paste v1.0.15
   Compiling autocfg v1.5.0
   Compiling terminfo v0.9.0
   Compiling syn v2.0.111
   Compiling shellexpand v3.1.1
   Compiling pcre2-sys v0.2.9 (https://github.com/fish-shell/rust-pcre2?tag=0.2.9-utf32#85b7afba)
   Compiling num-traits v0.2.19
   Compiling ppv-lite86 v0.2.21
   Compiling fish-build-man-pages v0.0.0 (/home/darkshadow/Projects/UNIX/fish/crates/build-man-pages)
   Compiling minimal-lexical v0.2.1
   Compiling foldhash v0.1.5
   Compiling bitflags v2.10.0
   Compiling allocator-api2 v0.2.21
   Compiling fish-gettext-mo-file-parser v0.0.0 (/home/darkshadow/Projects/UNIX/fish/crates/gettext-mo-file-parser)
   Compiling equivalent v1.0.2
   Compiling nom v7.1.3
   Compiling fish v4.2.1-snapshot (/home/darkshadow/Projects/UNIX/fish)
   Compiling rand_chacha v0.9.0
error[E0583]: file not found for module `pty`
   --> /var/xdg/darkshadow/cache/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.30.1/src/lib.rs:170:5
    |
170 |     pub mod pty;
    |     ^^^^^^^^^^^^
    |
    = help: to create the module `pty`, create file "/var/xdg/darkshadow/cache/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.30.1/src/pty.rs" or "/var/xdg/darkshadow/cache/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.30.1/src/pty/mod.rs"
    = note: if there is a `mod pty` elsewhere in the crate already, import it with `use crate::...` instead

error[E0583]: file not found for module `termios`
   --> /var/xdg/darkshadow/cache/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.30.1/src/sys/mod.rs:163:5
    |
163 |     pub mod termios;
    |     ^^^^^^^^^^^^^^^^
    |
    = help: to create the module `termios`, create file "/var/xdg/darkshadow/cache/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.30.1/src/sys/termios.rs" or "/var/xdg/darkshadow/cache/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.30.1/src/sys/termios/mod.rs"
    = note: if there is a `mod termios` elsewhere in the crate already, import it with `use crate::...` instead

   Compiling rand v0.9.2
   Compiling hashbrown v0.15.5
   Compiling phf v0.11.3
   Compiling globset v0.4.18
For more information about this error, try `rustc --explain E0583`.
   Compiling fnv v1.0.7
error: could not compile `nix` (lib) due to 2 previous errors
```

Bisects to d6108e5bc0d431df274a32696d6c6eb60b47d750 (Refactor `common::is_console_session`)

**Comment by faho** [comment]
I'm really not happy with nix's platform coverage.

See also #10090, where the "fs" feature failed on FreeBSD.

**Comment by krobelus** [comment]
@Darkshadow2 I cannot reproduce this; it works fine on OpenBSD 7.8 with Rust 1.90 when reverting 556be5c4a8c5d3c68a2b445c42e549e2b34a7070 and running `cargo build`.

> "/var/xdg/darkshadow/cache/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/nix-0.30.1/src/pty.rs"

this file should absolutely exist. What else is in that directory?
Can you try nuking this cargo cache dir (maybe the whole registry/ if needed).

**Comment by Darkshadow2** [comment]
@krobelus @faho You're right, blowing away the cache caused it to compile correctly. My apologies, that wasn't something I considered might be a problem. I didn't think to list the directory before I blew it away, but I had in my previous session and looking at it now there are at least 4 files there that weren't before.

**Comment by krobelus** [comment]
really strange.  Based on my testing, Cargo fetches all source files,
irrespective of which Cargo features are used.  And nix 0.30.1 was
published 8 months ago, so I'm not sure how this could have happened.

**Comment by Darkshadow2** [comment]
I'm not sure what happened either. I did delete everything in the cache folder a little over a month ago, so it happened between then and now (not related to anything, just clearing cache files). ~It's probably something dumb I managed to do rather than a fault with Cargo, though.~ Actually, it may be a job I have set up to run at the beginning of every month that cleans cache files. I probably added $XDG_CACHE_HOME to that without really thinking of it 🤦. So yeah, something dumb I did.
