### ISSUE TITLE
make_unique fails to build on GCC 6.1+

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#3759]
ac8b27fcb1 introduced the `make_unique` template function, which fails to build properly on GCC 6.1+ because of the new [`make_unique`](http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique) function introduced in C++14:

```
src/parser.cpp: In member function 'int parser_t::eval_acquiring_tree(const wcstring&, const io_chain_t&, block_type_t, moved_ref<parse_node_tree_t>)':
src/parser.cpp:615:105: error: call of overloaded 'make_unique(moved_ref<parse_node_tree_t>&, const wcstring&, parser_t*, int&)' is ambiguous
     execution_contexts.push_back(make_unique<parse_execution_context_t>(tree, cmd, this, exec_eval_level));
                                                                                                         ^
In file included from src/parser.cpp:10:0:
src/common.h:649:20: note: candidate: std::unique_ptr<_Tp> make_unique(Args&& ...) [with T = parse_execution_context_t; Args = {moved_ref<parse_node_tree_t>&, const std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, parser_t*, int&}]
 std::unique_ptr<T> make_unique(Args&&... args) {
                    ^~~~~~~~~~~
In file included from /usr/local/Cellar/gcc/6.3.0_1/include/c++/6.3.0/memory:81:0,
                 from src/parser.cpp:8:
/usr/local/Cellar/gcc/6.3.0_1/include/c++/6.3.0/bits/unique_ptr.h:790:5: note: candidate: typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = parse_execution_context_t; _Args = {moved_ref<parse_node_tree_t>&, const std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, parser_t*, int&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<parse_execution_context_t>]
     make_unique(_Args&&... __args)
     ^~~~~~~~~~~
```

**Comment by ridiculousfish** [comment]
Thanks, fixed as 009a677e0dd459f5bb269042207eaa16c31b673e
