### ISSUE TITLE
cannot build on OpenBSD

### ISSUE THREAD

**Issue by bonds** [fish-shell/fish-shell#3867]
- [X] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

n/a

**OS/terminal used**:

OpenBSD 6.0-stable amd_64

Fish 2.5.0 won't build on OpenBSD, instead the compiler spits out a bunch of errors. Fish 2.3.1 builds and runs fine using the older gcc (4.2.1), i.e. clear the CXX env variable with set -gx CXX and then run ````gmake distclean && ./configure && gmake````, but with the new gcc, i.e. 4.9.3 it spits out similar errors. Fish 2.4.0 with the new gcc spits out similar errors too. So, OpenBSD users are limited to using Fish 2.3.1 for now.

## Reproduction steps
1. set -gx CXX /usr/local/bin/x86_64-unknown-openbsd6.0-gcc-4.9.3
2. git clone https://github.com/fish-shell/fish-shell
3. cd fish-shell
3. git checkout 2.5.0
4. autoreconfigure --no-recursive
5. gmake

## Results

These are just the first lines of the *2nd* run of gmake. The first run a bunch of stuff built successfully before ending with errors. The full output is a number of megabytes uncompressed...

```console
  FISH_BUILD_VERSION = '2.5.0'^O
  CXX = '/usr/local/bin/x86_64-unknown-openbsd6.0-gcc-4.9.3 -std=c++11'^O
  CXXFLAGS = '-g -O2 -fno-exceptions -Wextra -Ipcre2-10.21/src '^O
  MKDIR_P = './install-sh -c -d'^O
  CXX LD   fish^O
obj/fallback.o: In function `lrand48_r(drand48_data*, long*)':
src/fallback.cpp:242: warning: warning: rand_r() is not random, it is deterministic.
obj/common.o: In function `format_long_safe(wchar_t*, long)':
src/common.cpp:674: warning: warning: wcscpy() is almost always misused, please use wcslcpy()
pcre2-10.21/.libs/libpcre2-32.a(libpcre2_32_la-pcre2_error.o): In function `pcre2_get_error_message_32':
src/pcre2_error.c:302: warning: warning: sprintf() is often misused, please use snprintf()
obj/autoload.o: In function `_Alloc_hider':
/usr/local/include/c++/4.9.3/bits/basic_string.h:275: undefined reference to `std::basic_string<wchar_t,std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_S_empty_rep_storage'
obj/autoload.o: In function `lru_node_t':
src/lru.h:33: undefined reference to `std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t>> const&)'
obj/autoload.o: In function `autoload_t::autoload_t(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, builtin_script_t const*, unsigned long)':
src/autoload.cpp:54: undefined reference to `std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::basic_string(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&)'
obj/autoload.o: In function `std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_M_dispose(std::allocator<wchar_t> const&)':
/usr/local/include/c++/4.9.3/bits/basic_string.h:249: undefined reference to `std::basic_string<wchar_t,std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_M_destroy(std::allocator<wchar_t> const&)'
obj/autoload.o: In function `~vector':
/usr/local/include/c++/4.9.3/bits/stl_vector.h:425: undefined reference to `std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::_Rep::_S_empty_rep_storage'
```

**Comment by bonds** [comment]
If it would be any help, I'm happy to put together an OpenBSD VM (virtualbox or qemu) with everything setup to easily reproduce the issue, and post that somewhere so a dev can download it and use it.

**Comment by ridiculousfish** [comment]
This looks like you're either not linking with libstdc++, or are linking with a version of libstdc++ for gcc 4.2 instead of 4.9. Does that hint help?

**Comment by krader1961** [comment]
I don't have OpenBSD setup but have no problem building fish on FreeBSD 12.0 or DragonflyBSD. So, like @ridiculousfish, I'm inclined to think there is something wrong with your build environment.

**Comment by bonds** [comment]
It looks like there's no prebuilt package for libstdc++ on my version of OpenBSD, so I'll have to try and build it myself. I'll report back if I get it working. Thanks for the hint!

**Comment by bonds** [comment]
Correction, fishshell 2.4.0 builds fine with the builtin GCC on OpenBSD 6.0, but 2.5.0 does not.

**Comment by bonds** [comment]
I took a stab at building gcc 4.9.3 and the libstdc++ that comes with it, but its not going to be a quick fix and I don't think I'm going to get it across the finish line. I think the thing to do is to wait for gcc and libstdc++ to be updated in OpenBSD, hopefully in 6.1 in 6.2, and try again. I suggest this is a WNF unless y'all feel otherwise. I'll miss living on the cutting edge with y'all, but even fishshell 2.4.0 is pretty awesome vs the alternatives.

So long, and thanks for all the fish.
