### ISSUE TITLE
Build failure on older GCC since 364c6001dc

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#7554]
364c6001dc broke the build on GCC 4.8 (RHEL 7) with the following:

```
[   66s] In file included from /home/abuild/rpmbuild/BUILD/fish-3.1.2-1772-g1083cd264/src/builtin.cpp:19:0:
[   66s] /home/abuild/rpmbuild/BUILD/fish-3.1.2-1772-g1083cd264/config.h:185:42: error: missing binary operator before token "("
[   66s]  #if defined(__clang__) && __has_attribute(warn_unused_result)
[   66s]                                           ^
```

**Comment by faho** [comment]
So apparently we need to guard this with `#if defined __has_attribute` - see https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005fattribute.html.

**Comment by faho** [comment]
Okay, clang recommends defining a stub macro if it's not defined - http://clang.llvm.org/docs/LanguageExtensions.html#has-attribute.

I'm just going to do that.

**Comment by faho** [comment]
@zanchey Can you confirm that works?

**Comment by zanchey** [comment]
Yes, looks good.

**Comment by ridiculousfish** [comment]
0028dce9ed61939c12b3180878e326bfbca2acb9 adds a Dockerfile to build and test locally on centos7 so we can more easily check gcc 4.8 builds.
