### ISSUE TITLE
Unable to build fish in debian/oldstable due to compiler error in ‘void universal_notifier_inotify_t::reestablish_watch()’

### ISSUE THREAD

**Issue by bentolor** [fish-shell/fish-shell#1476]
I'm unable to build currently fish in debian/oldstable (a983318)

It git bisected it down to 38da76804e8e1c0e97ba4f59711b64f0637ced50 Implement shared memory strategy for universal variable notifications

From what I've seen during bisecting, there might be more than one error since that (I saw different errors I think).

```
    g++ -g -O2 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -fno-exceptions -Wall -Wno-sign-compare -D_GNU_SOURCE=1 -D_ISO99_SOURCE=1  -DLOCALEDIR=\"/usr/local/share/locale\" -DPREFIX=L\"/usr/local\" -DDATADIR=L\"/usr/local/share\" -DSYSCONFDIR=L\"/usr/local/etc\" -DBINDIR=L\"/usr/local/bin\" -DDOCDIR=L\"/usr/local/share/doc/fish\"   -DFISH_BUILD_VERSION=\"1.23.1-2221-ga983318\"  -c -o input_common.o input_common.cpp
    g++ -g -O2 -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -fno-exceptions -Wall -Wno-sign-compare -D_GNU_SOURCE=1 -D_ISO99_SOURCE=1  -DLOCALEDIR=\"/usr/local/share/locale\" -DPREFIX=L\"/usr/local\" -DDATADIR=L\"/usr/local/share\" -DSYSCONFDIR=L\"/usr/local/etc\" -DBINDIR=L\"/usr/local/bin\" -DDOCDIR=L\"/usr/local/share/doc/fish\"   -DFISH_BUILD_VERSION=\"1.23.1-2221-ga983318\"  -c -o event.o event.cpp
    env_universal_common.cpp: In member function ‘void universal_notifier_inotify_t::reestablish_watch()’:
    env_universal_common.cpp:1641: error: ‘IN_EXCL_UNLINK’ was not declared in this scope
    make: *** [env_universal_common.o] Fehler 1
```
