### ISSUE TITLE
Call to setupterm fails to compile due to dropping const

### ISSUE THREAD

**Issue by Benabik** [fish-shell/fish-shell#1142]
Introduced in 2c39d5b6c00f6f73af1342eb8f76866aae4de1a3

```
input.cpp:363:17: error: no matching function for call to 'setupterm'
            if (setupterm(default_term.c_str(), STDOUT_FILENO, &errret) == ERR)
                ^~~~~~~~~
/usr/include/term.h:759:28: note: candidate function not viable: 1st argument
      ('const_pointer' (aka 'const char *')) would lose const qualifier
extern NCURSES_EXPORT(int) setupterm (NCURSES_CONST char *,int,int *);
                           ^
```

On OS X 10.9 and Fedora 19 x86_64
