### ISSUE TITLE
build broken by ncurses/term.h in builtin_set_color on FreeBSD

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#594]
a355cf2 breaks the build on FreeBSD 9.1, presumably due to some interaction between ncurses.h and term.h.

```
g++ -I/usr/local/include/ -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -Wall -DLOCALEDIR=\"/opt/share/locale\" -DPREFIX=L\"/opt\" -DDATADIR=L\"/opt/share\" -DSYSCONFDIR=L\"/opt/etc\"  -c builtin.cpp
In file included from builtin_set_color.cpp:19,
                 from builtin.cpp:393:
/usr/include/term.h:755: error: expected unqualified-id before numeric constant
/usr/include/term.h:755: error: expected `)' before numeric constant
*** [builtin.o] Error code 1
```
